version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: geolocation-db
    environment:
      POSTGRES_USER: alfinkly
      POSTGRES_PASSWORD: asd
      POSTGRES_DB: geolocation
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: geolocation-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: geolocation
      PORT: 8080

  web:
    build: ./web
    container_name: geolocation-web
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: