version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: geolocation-db
    environment:
      POSTGRES_USER: deaspecty
      POSTGRES_PASSWORD: asdasdasd
      POSTGRES_DB: geolocation
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deaspecty -d geolocation" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: geolocation-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: deaspecty
      DB_PASSWORD: asdasdasd
      DB_NAME: geolocation
      PORT: 8080
      IPINFO_TOKEN: d5b94e63d51f03

  web:
    build: ./web
    container_name: geolocation-web
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata: